### ISSUE TITLE
tuning curve with Tsd

### ISSUE THREAD

**Issue by BalzaniEdoardo** [pynapple-org/pynapple#250]
Hi again!

Currently  ` nap.compute_2d_tuning_curves_continuous` does not work if you try to compute a tuning curve passing a Tsd as argument. 

```python
tsd = nap.Tsd(t=np.arange(10),d=np.arange(10))
position = nap.TsdFrame(t=np.arange(10), d=np.hstack((np.arange(10)[:, np.newaxis], np.arange(10)[:, np.newaxis])))
nap.compute_2d_tuning_curves_continuous(tsd, features=position, nb_bins=3)
```

Results in the following error
```
Traceback (most recent call last):
  File "/Users/ebalzani/.pyenv/versions/nemos/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-cee74cf41d0e>", line 1, in <module>
    nap.compute_2d_tuning_curves_continuous(tsd, features=position, nb_bins=3)
  File "/Users/ebalzani/.pyenv/versions/3.11.8/envs/nemos/lib/python3.11/site-packages/pynapple/process/tuning_curves.py", line 536, in compute_2d_tuning_curves_continuous
    tc_np = np.zeros((tsdframe.shape[1], nb_bins[0], nb_bins[1])) * np.nan
                      ~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range
```

With pynapple Version: 0.6.1.  this is with python 3.11.8, on a mac. I don't think the interpreter and os matters, it is really the assumption of the input being a frame (ndim==2).

It would be nice to have the function working for Tsd as well.

Cheers,
Edoardo

**Comment by BalzaniEdoardo** [comment]
this happens also in the 1d tuning function, continuing the example above,

```python
>>> nap.compute_1d_tuning_curves_continuous(tsd, position[:,0], nb_bins=3)
Traceback (most recent call last):
  File "/Users/ebalzani/.pyenv/versions/nemos/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-7de94540f215>", line 1, in <module>
    nap.compute_1d_tuning_curves_continuous(tsd, position[:,0], nb_bins=3)
  File "/Users/ebalzani/.pyenv/versions/3.11.8/envs/nemos/lib/python3.11/site-packages/pynapple/process/tuning_curves.py", line 452, in compute_1d_tuning_curves_continuous
    tmp = tsdframe.as_dataframe().groupby(idx).mean()
          ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Tsd' object has no attribute 'as_dataframe'
```
